import React, { useState } from 'react';
import * as Icons from 'lucide-react';
import { AccordionCard } from '../common/AccordionCard';
import { InfoTooltip } from '../common/InfoTooltip';
import { AI_RECOMMENDATIONS } from '../../data/mockData';
import { dashboardInfo } from '../../data/dashboardInfo';

export const AIRecommendationEngineModule: React.FC = () => {
  const [filterPriority, setFilterPriority] = useState<string>('All');
  const [executedActions, setExecutedActions] = useState<Record<string, boolean>>({});

  const filteredRecs = AI_RECOMMENDATIONS.filter((rec) =>
    filterPriority === 'All' ? true : rec.priority === filterPriority
  );

  const handleExecuteAction = (id: string) => {
    setExecutedActions((prev) => ({ ...prev, [id]: true }));
  };

  return (
    <div className="space-y-8 animate-in fade-in duration-300">
      {/* Module Banner */}
      <div className="mantra-card p-6 border-l-4 border-l-purple-500 bg-gradient-to-r from-purple-900 via-[#0A2E5C] to-slate-900 text-white relative overflow-hidden">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div className="flex items-center space-x-4">
            <div className="w-12 h-12 rounded-2xl bg-purple-600 flex items-center justify-center shadow-lg shadow-purple-500/30 shrink-0">
              <Icons.Sparkles className="w-6 h-6 text-white animate-pulse" />
            </div>
            <div>
              <div className="mantra-kicker text-purple-300">PREDICTIVE PRESCRIPTIVE INTELLIGENCE</div>
              <h2 className="text-xl md:text-2xl font-bold">MantraCare AI Recommendation Engine</h2>
              <p className="text-xs text-blue-200/80 mt-1">
                Real-time prescriptive action feed generated by continuous ML modeling of workforce health & financial claims.
              </p>
            </div>
          </div>
          <div className="flex items-center space-x-2">
            <span className="px-3 py-1.5 rounded-full text-xs font-extrabold bg-purple-500 text-white shadow">
              {AI_RECOMMENDATIONS.length} Active Prescriptions
            </span>
          </div>
        </div>
      </div>

      {/* Filter Tabs */}
      <div className="flex items-center justify-between">
        <div>
          <div className="mantra-kicker">STRATEGIC ACTION FEED</div>
          <div className="flex items-center gap-1.5">
            <h3 className="text-lg font-bold text-slate-900 dark:text-white">
              Prioritized Enterprise Interventions
            </h3>
            <InfoTooltip title={dashboardInfo.aiRecommendations.title} description={dashboardInfo.aiRecommendations.description} />
          </div>
        </div>

        <div className="flex items-center space-x-1 p-1 bg-slate-200 dark:bg-slate-800 rounded-xl text-xs">
          {['All', 'Critical', 'High', 'Strategic'].map((prio) => (
            <button
              key={prio}
              onClick={() => setFilterPriority(prio)}
              className={`px-3 py-1.5 rounded-lg font-bold transition-all ${
                filterPriority === prio
                  ? 'bg-purple-600 text-white shadow'
                  : 'text-slate-600 dark:text-slate-300 hover:text-slate-900 dark:hover:text-white'
              }`}
            >
              {prio}
            </button>
          ))}
        </div>
      </div>

      {/* Accordion Insight Feed List */}
      <div className="space-y-4">
        {filteredRecs.map((rec, index) => {
          const isExecuted = executedActions[rec.id];

          return (
            <AccordionCard
              key={rec.id}
              id={rec.id}
              title={`${rec.type} — ${rec.title}`}
              badge={rec.priority}
              badgeColor={
                rec.priority === 'Critical'
                  ? 'bg-rose-100 dark:bg-rose-950 text-rose-700 dark:text-rose-300'
                  : rec.priority === 'High'
                  ? 'bg-amber-100 dark:bg-amber-950 text-amber-700 dark:text-amber-300'
                  : 'bg-purple-100 dark:bg-purple-950 text-purple-700 dark:text-purple-300'
              }
              subtitle={rec.teaser}
              defaultExpanded={index === 0}
              icon={
                rec.type.includes('Burnout')
                  ? 'Flame'
                  : rec.type.includes('Adoption')
                  ? 'Users'
                  : rec.type.includes('ROI')
                  ? 'TrendingUp'
                  : rec.type.includes('Claims')
                  ? 'Stethoscope'
                  : 'ShieldAlert'
              }
            >
              <div className="space-y-5">
                {/* Metrics Breakdown Grid */}
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
                  <div className="p-3 rounded-xl bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800">
                    <div className="text-[10px] font-bold text-slate-500 dark:text-slate-400 uppercase">
                      Est. Annual Savings
                    </div>
                    <div className="text-lg font-extrabold text-emerald-600 dark:text-emerald-400 mt-1">
                      {rec.estimatedSavings}
                    </div>
                  </div>

                  <div className="p-3 rounded-xl bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800">
                    <div className="text-[10px] font-bold text-slate-500 dark:text-slate-400 uppercase">
                      Affected Population
                    </div>
                    <div className="text-lg font-extrabold text-blue-600 dark:text-blue-400 mt-1">
                      {rec.affectedEmployees.toLocaleString()} Employees
                    </div>
                  </div>

                  <div className="p-3 rounded-xl bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800">
                    <div className="text-[10px] font-bold text-slate-500 dark:text-slate-400 uppercase">
                      Location / Scope
                    </div>
                    <div className="text-sm font-bold text-slate-900 dark:text-white mt-1">
                      {rec.location || 'Global'} ({rec.department || 'All'})
                    </div>
                  </div>

                  <div className="p-3 rounded-xl bg-purple-50 dark:bg-purple-950/40 border border-purple-200 dark:border-purple-900">
                    <div className="text-[10px] font-bold text-purple-700 dark:text-purple-300 uppercase">
                      AI Model Confidence
                    </div>
                    <div className="text-lg font-black text-purple-600 dark:text-purple-400 mt-1">
                      {rec.confidenceScore}% Confidence
                    </div>
                  </div>
                </div>

                {/* Expected Business Impact */}
                <div className="p-4 rounded-xl bg-blue-50/60 dark:bg-blue-950/40 border border-blue-100 dark:border-blue-900 text-xs">
                  <div className="font-bold text-blue-900 dark:text-blue-200 uppercase tracking-wider mb-1">
                    EXPECTED BUSINESS IMPACT
                  </div>
                  <p className="text-slate-700 dark:text-slate-300 leading-relaxed font-medium">
                    {rec.expectedImpact}
                  </p>
                </div>

                {/* Recommended Action & Trigger Button */}
                <div className="p-4 rounded-xl bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 flex flex-col md:flex-row md:items-center justify-between gap-4">
                  <div className="flex items-start space-x-3">
                    <Icons.CheckCircle2 className="w-5 h-5 text-emerald-500 shrink-0 mt-0.5" />
                    <div>
                      <div className="text-xs font-bold text-slate-900 dark:text-white">
                        Prescribed Action Step:
                      </div>
                      <p className="text-xs text-slate-600 dark:text-slate-300 mt-0.5">
                        {rec.recommendedAction}
                      </p>
                    </div>
                  </div>

                  <button
                    type="button"
                    disabled={isExecuted}
                    onClick={() => handleExecuteAction(rec.id)}
                    className={`px-5 py-2.5 rounded-xl font-bold text-xs shadow-lg transition-all shrink-0 flex items-center space-x-2 ${
                      isExecuted
                        ? 'bg-emerald-600 text-white cursor-default'
                        : 'bg-purple-600 hover:bg-purple-500 text-white'
                    }`}
                  >
                    {isExecuted ? (
                      <>
                        <Icons.Check className="w-4 h-4" />
                        <span>Action Triggered & Queued</span>
                      </>
                    ) : (
                      <>
                        <Icons.Play className="w-4 h-4 fill-white" />
                        <span>Deploy Prescription</span>
                      </>
                    )}
                  </button>
                </div>
              </div>
            </AccordionCard>
          );
        })}
      </div>
    </div>
  );
};
