export type DashboardInfo = {
  title: string;
  description: string;
};

export const dashboardInfo = {
  executiveSummary: {
    title: 'Executive overview',
    description:
      'Brings together the highest-signal EAP, financial, utilisation, and clinical outcomes. Use it to understand programme health before exploring a specific area.',
  },
  financialRoi: {
    title: 'Financial ROI',
    description:
      'Estimates the financial value generated by the wellbeing programme relative to investment. Use it to understand return, savings, and where value is being created.',
  },
  aiInsights: {
    title: 'AI insights',
    description:
      'Highlights patterns across dashboard data that may need attention. Use these signals to identify risks, opportunities, and practical next actions faster.',
  },
  aiRecommendations: {
    title: 'AI recommendations',
    description:
      'Prioritises data-informed actions for workforce health and programme performance. Use the feed to focus attention where an intervention may have the greatest impact.',
  },
  scorecard: {
    title: 'Value scorecard',
    description:
      'Summarises the programme outcomes that matter most to leadership: financial return, clinical impact, and employee adoption.',
  },
  roiTrend: {
    title: 'EAP ROI trend',
    description:
      'Compares cumulative programme return with programme cost over time. Use the direction and gap between the lines to assess whether value is accelerating.',
  },
  referralSource: {
    title: 'EAP referral source',
    description:
      'Shows how employees enter the EAP, including self-referrals and manager referrals. Use the mix to understand access behaviour and outreach opportunities.',
  },
  roiProjection: {
    title: 'ROI projection',
    description:
      'Forecasts cumulative savings against expected investment over five years. Use it to understand the likely long-term value of current adoption and outcome trends.',
  },
  departmentRoi: {
    title: 'Department ROI comparison',
    description:
      'Compares utilisation, claims savings, and return across business units. Use it to identify where the programme is creating the most value and where support may be needed.',
  },
  aiCoachMetrics: {
    title: 'AI coach metrics',
    description:
      'Shows how employees use the AI coach and whether that engagement leads to goals, safety escalations, and positive user ratings.',
  },
  intentCategories: {
    title: 'Intent categories',
    description:
      'Groups AI coach conversations by the topics employees ask about most. Use the mix to understand demand and guide content or care pathway priorities.',
  },
  regionalBenchmarks: {
    title: 'Regional benchmarks',
    description:
      'Compares ROI, usage, and workforce risk across regions using the current reporting period. Use it to spot meaningful geographic differences rather than isolated totals.',
  },
  teamClimate: {
    title: 'Team climate',
    description:
      'Combines manager activity, referrals, burnout risk, and wellbeing scores at team level. Use it to identify teams that may benefit from targeted manager support.',
  },
  riskMatrix: {
    title: 'Department risk matrix',
    description:
      'Shows how common stress, burnout, anxiety, sleep, and physical wellbeing concerns are across departments. Use it to prioritise focused workforce interventions.',
  },
  reportsLibrary: {
    title: 'Executive reports library',
    description:
      'Collects board-ready reports and exports for leadership review. Use the library to find the right level of detail for governance, finance, or operational decisions.',
  },
  administration: {
    title: 'Administration status',
    description:
      'Summarises programme configuration, access, integrations, and security controls. Use it to confirm the dashboard is configured and operating as intended.',
  },
  careBreakdown: {
    title: 'Consultation breakdown',
    description:
      'Shows care volume, wait time, resolution, and avoided cost by consultation type. Use it to understand demand and access performance across care pathways.',
  },
  chronicPathways: {
    title: 'Chronic care pathways',
    description:
      'Compares enrolment, adherence, clinical improvement, and avoided hospital activity across chronic condition programmes.',
  },
  clinicalOutcomes: {
    title: 'Clinical outcomes',
    description:
      'Compares measured outcomes before and after care using the programme’s clinical scales. Use it to understand whether care is producing meaningful improvement.',
  },
  engagementBreakdown: {
    title: 'Engagement breakdown',
    description:
      'Shows how employees move from onboarding into active use and which services they choose. Use it to identify adoption friction and content demand.',
  },
  womenCare: {
    title: 'Women’s care utilisation',
    description:
      'Shows enrolment, retention, and return generated by women’s health pathways. Use it to understand reach and programme performance for specialised care.',
  },
  eapDepartmentBreakdown: {
    title: 'EAP department breakdown',
    description:
      'Compares registration, active use, sessions, crisis cases, recovery, and ROI by department. Use it to focus outreach and support where it can have the most impact.',
  },
  modules: {
    'exec-summary': {
      title: 'Executive overview',
      description:
        'Brings together the highest-signal EAP, financial, utilisation, and clinical outcomes so leadership can assess programme health at a glance.',
    },
    'business-impact': {
      title: 'Business impact',
      description:
        'Connects workforce wellbeing activity to financial outcomes, savings, productivity, and business value for investment decisions.',
    },
    'workforce-health': {
      title: 'Workforce health',
      description:
        'Shows workforce health risks, needs, and outcomes so teams can target support where it is most useful.',
    },
    'employee-experience': {
      title: 'Employee experience',
      description:
        'Shows how employees discover, access, and use wellbeing services. Use it to understand adoption and remove friction from care.',
    },
    'organization-insights': {
      title: 'Organization insights',
      description:
        'Compares workforce patterns across regions, offices, departments, and managers to support focused operational decisions.',
    },
    'ai-intelligence': {
      title: 'AI intelligence',
      description:
        'Surfaces patterns, risks, and recommended actions from dashboard data to help decision-makers focus attention faster.',
    },
    'reports-admin': {
      title: 'Reports and administration',
      description:
        'Provides controlled reporting and programme administration tools for distributing insight and maintaining the dashboard setup.',
    },
  } satisfies Record<string, DashboardInfo>,
  kpis: {
    'kpi-roi': {
      title: 'Overall EAP ROI',
      description:
        'Shows the return generated for each dollar invested in the EAP. Use it as a top-line view of programme value, alongside the trend and supporting savings metrics.',
    },
    'kpi-cost': {
      title: 'Total programme cost',
      description:
        'Shows the annual EAP investment included in the financial model. Compare it with gross return and net savings to understand the cost-to-value relationship.',
    },
    'kpi-savings': {
      title: 'Healthcare savings',
      description:
        'Estimates avoided healthcare costs associated with earlier support and reduced claims. Use it to understand the medical cost contribution to overall programme value.',
    },
    'kpi-net-savings': {
      title: 'Net savings',
      description:
        'Shows gross programme return after deducting annual EAP cost. It is the clearest view of the financial gain available after investment.',
    },
    'kpi-reg-rate': {
      title: 'Registration rate',
      description:
        'Shows the share of eligible employees who have registered for the EAP. Use it to assess reach and identify populations that may need stronger awareness efforts.',
    },
    'kpi-mau': {
      title: 'Monthly active users',
      description:
        'Shows how many employees actively use EAP services each month. Use it with registration to distinguish initial reach from ongoing engagement.',
    },
    'kpi-clinical-imp': {
      title: 'Clinical improvement',
      description:
        'Shows the share of measured participants achieving a meaningful clinical improvement. Use it to understand whether engagement is translating into better outcomes.',
    },
    'kpi-csat': {
      title: 'Care satisfaction',
      description:
        'Shows how employees rate their care experience. Use it as a quality signal alongside access, utilisation, and clinical results.',
    },
    'kpi-time-to-appt': {
      title: 'Time to appointment',
      description:
        'Shows the typical time employees wait for an appointment. Lower wait times generally indicate easier access and less friction at the start of care.',
    },
    'kpi-crisis': {
      title: 'Crisis response',
      description:
        'Shows the share of urgent cases receiving timely support. Use it to monitor a high-priority safety and service responsiveness measure.',
    },
    'kpi-cost-per-active': {
      title: 'Cost per active user',
      description:
        'Shows programme cost distributed across monthly active users. Use it to understand efficiency as engagement changes over time.',
    },
  } satisfies Record<string, DashboardInfo>,
} as const;

export type DashboardInfoKey = Exclude<keyof typeof dashboardInfo, 'kpis' | 'modules'>;

export function getKpiInfo(kpi: { id: string; title: string; description?: string; kicker?: string }): DashboardInfo {
  return (
    dashboardInfo.kpis[kpi.id as keyof typeof dashboardInfo.kpis] ?? {
      title: kpi.title,
      description:
        kpi.description ??
        `Shows ${kpi.title.toLowerCase()} for the current reporting population. Use the trend to compare performance with the selected comparison period.`,
    }
  );
}
